#!/usr/bin/env bash
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

time=3
bias=0
alpha="0.9"

kbd=$(light -L | grep kbd)

light -As $kbd 5

light=$(light -s $kbd)
light=$(echo $light | awk '{print int($1+0.5)}')
scaled=$(echo "scale=2; $light / 100.0" | bc)


if [ "$light" -lt "34" ]
then
    ${__dir}/notify-progress "Keyboard Low" "$light"
    avizo-client --image-resource="brightness_low" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
elif [ "$light" -lt "66" ]
then
    ${__dir}/notify-progress "Keyboard Med" "$light"
    avizo-client --image-resource="brightness_medium" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
elif [ "$light" -lt "101" ]
then
    ${__dir}/notify-progress "Keyboard High" "$light"
    avizo-client --image-resource="brightness_high" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
fi
