#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

TARGET=$(light -L | grep backlight/auto)
NAME="Screen"

for arg do
  shift
  if [ "$arg" = "--keyboard" ]; then
    TARGET=$(light -L | grep kbd)
    NAME="Keyboard"
    continue
  fi
  set -- "$@" "$arg"
done

STEP=${2:-4}


if [[ "$1" == "down" ]]; then
    light -Us $TARGET $STEP
elif [[ "$1" == "up" ]]; then
    light -As $TARGET $STEP
fi

light=$(light -s $TARGET)
light=$(echo $light | awk '{print int($1+0.5)}')
scaled=$(echo "scale=2; $light / 100.0" | bc)

 ~/.config/sway/actions/notify-progress "$NAME Brightness $light%" "$light"
