#!/usr/bin/env sh

swaylock_process=$(pgrep swaylock  | tail -1)
if [[ ! -z "$swaylock_process" ]]; then
  exit 0
fi

# TODO(JL): Grab resolution from swaymsg
# /usr/lib/xscreensaver/gluqlo -ampm -s 1.0 -r 2882x1800 &
/usr/lib/xscreensaver/gluqlo -ampm -s 0.95 -r 2888x1800 &
swaylock -c 00000000 ; killall gluqlo
