#!/usr/bin/env bash

# Constants
TOTAL_UNITS=33
COVERED_UNIT="▓"
PARTIAL_UNIT="▒"
UNCOVERED_UNIT="░"
EXPIRE_TIME="3000"
TEMP_FILE="/tmp/notify-progress"

# Helpers
print_times () {
    local text="$1"
    local i="$2"
    local result=""

    while [[ $i -gt 0 ]]; do
        result+="$text"
        i=$[$i-1]
    done

    echo "$result"
}

notify () {
    return $(notify-send.sh --expire-time=$EXPIRE_TIME --replace-file=$1 "$2" "$3")
}

# Args
title="$1"
progress="$2"

# Main

if [[ $(echo "$progress < 0" | bc -l) -eq 1 ]]; then
    progress=0
elif [[ $(echo "$progress > 100" | bc -l) -eq 1 ]]; then
    progress=100
fi

covered_units=$(echo "$progress * $TOTAL_UNITS / 100" | bc)
partial_units=0
uncovered_units=$[$TOTAL_UNITS-$covered_units]


covered_units_decimal=$(echo "scale=1; $progress * $TOTAL_UNITS / 100" | bc -l)
if [[ "$covered_units_decimal" != *".0"* && "$covered_units_decimal" != "0" ]]; then
    uncovered_units=$[$uncovered_units-1]
    partial_units=1
fi

progressbar=""
progressbar+=$(print_times $COVERED_UNIT $covered_units)
progressbar+=$(print_times $PARTIAL_UNIT $partial_units)
progressbar+=$(print_times $UNCOVERED_UNIT $uncovered_units)

echo $title
echo $progressbar

notify "$TEMP_FILE" "$title" "$progressbar" || \
(rm "$TEMP_FILE" && notify "$TEMP_FILE" "$title" "$progressbar")
