#!/usr/bin/env sh

set -e

TEMP_FILE="/tmp/pick-color"
EXPIRE_TIME="10000"
CLIPBOARD=0

# TODO: Mako notification?

for arg do
  shift
  if [ "$arg" = "--clipboard" ]; then
    CLIPBOARD=1
    continue
  fi
  set -- "$@" "$arg"
done

pixel_colors=$(grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | tail -n 1)
pixel_color=""

case "$1" in
rgb)
  pixel_color=$(echo "$pixel_colors" | cut -d ' ' -f 2)
  ;;

hex)
  pixel_color=$(echo "$pixel_colors" | cut -d ' ' -f 4)
  ;;

srgb)
  pixel_color=$(echo "$pixel_colors" | cut -d ' ' -f 6)
  ;;

*)
  exit 1
  ;;
esac


if [[ $CLIPBOARD -eq 1 ]]; then
  wl-copy "$pixel_color"
else
  notify-send.sh --expire-time=$EXPIRE_TIME --urgency=critical --replace-file=TEMP_FILE "Color Picker" "$1: $pixel_color"
  echo "$pixel_color"
fi
