#!/usr/bin/env sh

killall -s SIGINT wf-recorder
while pgrep -x wf-recorder >/dev/null; do
  sleep 0.1
done
~/.config/sway/actions/signal-waybar recording
pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
