#!/usr/bin/env sh

set -e

FILENAME=~/Desktop/$(date +"%Y-%m-%d-%T").mp4
FLAG=""

# TODO: Swaynag "You're recording your screen"?
# TODO: Mako notification?

for arg do
  shift
  if [ "$arg" = "--audio" ]; then
    FLAG="--audio"
    continue
  fi
  set -- "$@" "$arg"
done

play_beep () {
  pacat --file-format=wav ~/.config/sway/sounds/volume.wav
  # sleep 0.5
  # pacat --file-format=wav ~/.config/sway/sounds/volume.wav
  # sleep 0.5
  # pacat --file-format=wav ~/.config/sway/sounds/volume.wav
  # sleep 0.5
}

~/.config/sway/actions/record-stop

case "$1" in
screen)
  play_beep
  wf-recorder $FLAG -f "$FILENAME"
  ;;

area)
  play_beep
  wf-recorder $FLAG -g "$(slurp)" -f "$FILENAME"
  ;;

window)
  play_beep
  wf-recorder $FLAG -g "$(~/.config/sway/actions/slurp-window)" -f "$FILENAME"
  ;;

*)
  exit 1
  ;;
esac

pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
