#!/usr/bin/env sh

set -e

FILENAME=~/Desktop/$(date +"%Y-%m-%d-%T").png

# TODO(JL): Add Clipboard option
# TODO: Mako notification?

CLIPBOARD=0
for arg do
  shift
  [ "$arg" = "--clipboard" ] && continue
  CLIPBOARD=1
  set -- "$@" "$arg"
done

case "$1" in
screen)
  grim "$FILENAME"
  ;;

area)
  slurp | grim -g - "$FILENAME"
  ;;

window)
  ~/.config/sway/actions/slurp-window | grim -g - "$FILENAME"
  ;;

*)
  exit 1
  ;;
esac

if [[ $CLIPBOARD -eq 1 ]]; then
  wl-copy < "$FILENAME"
  rm "$FILENAME"
fi


pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
