#!/usr/bin/env sh

set -e

FILENAME=~/Desktop/$(date +"%Y-%m-%d-%T").png
CLIPBOARD=0
EDIT=0

# TODO(JL): Add Clipboard option
# TODO: Mako notification?

for arg do
  shift
  if [ "$arg" = "--clipboard" ]; then
    CLIPBOARD=1
    continue
  fi
  if [ "$arg" = "--edit" ]; then
    EDIT=1
    continue
  fi
  set -- "$@" "$arg"
done

case "$1" in
screen)
  ~/.config/sway/actions/slurp-screen | grim -g - "$FILENAME"
  ;;

area)
  slurp | grim -g - "$FILENAME"
  ;;

window)
  ~/.config/sway/actions/slurp-window | grim -g - "$FILENAME"
  ;;

*)
  exit 1
  ;;
esac

if [[ $CLIPBOARD -eq 1 ]]; then
  wl-copy < "$FILENAME"
  rm "$FILENAME"
fi

if [[ $EDIT -eq 1 ]]; then
  swappy -f "$FILENAME"
  rm "$FILENAME"
fi


pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
