#!/usr/bin/env sh

set -e

FILENAME=~/Desktop/$(date +"%Y-%m-%d-%T").mp4

# TODO(JL): Add Clipboard option
# TODO: Mako notification?

case "$1" in
screen)
  grim "$FILENAME"
  ;;

area)
  slurp | grim -g - "$FILENAME"
  ;;

window)
  ~/.config/sway/actions/slurp-window | grim -g - "$FILENAME"
  ;;

*)
  exit 1
  ;;
esac

if [[ $* == *-c* ]]; then
  wl-copy < "$FILENAME"
  rm "$FILENAME"
fi


pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
