#!/usr/bin/env sh

set -e

# SIGNALS
MODULE_RECORDING=1
MODULE_MUTE=2

send_signal () {
  pkill -SIGRTMIN+$1 waybar
}

case "$1" in
recording)
  send_signal $MODULE_RECORDING
  ;;

mute)
  send_signal $MODULE_MUTE
  ;;

*)
  exit 1
  ;;
esac
