#!/bin/bash

if [[ "$(pgrep wf-recorder)" ]]; then
  ~/.config/sway/actions/record-stop
  exit 1
fi

# https://gist.github.com/progandy/bff675311aa2c3b777a37abe81aa4b4d
# sway-mirror OPTIONS
# SDL_VIDEODRIVER=wayland stream
# SDL_VIDEODRIVER=x11 stream
# sway-mirror --output LVDS-1

# TODO: Swaynag "You're sharing your screen"?
# TODO: Mako notification?

instance=sway-mirror$$
wf-recorder "$@" -c rawvideo -m sdl -f pipe:$instance &
pid=$!
trap "kill -s SIGINT $pid 2> /dev/null ; ~/.config/sway/actions/record-stop" EXIT

~/.config/sway/actions/signal-waybar recording

while read type ; read name ; do
	if [[ $type == '"close"' && $name == "\"pipe:$instance\"" ]]; then
		break
	fi
done < <(swaymsg -mt subscribe '["window"]' | jq --unbuffered .change,.container.name)

# Wait and see if wf-recorder process dies
# sleep 1
# if ps -p $pid > /dev/null; then
	# wf-recorder is still alive, which means only the mirror instance was closed
# 	exit 0
# fi

# Ensure wf-recorder process is killed
~/.config/sway/actions/record-stop --silent

trap - EXIT
