#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

STEP=${2:-3}

prev_amixer_result=$(amixer get Master)
prev_vol=$(echo "$prev_amixer_result" | grep -Po "[0-9]+(?=%)" | tail -1)
prev_state=$(echo "$prev_amixer_result" | grep -o "off" | head -n 1)

next_amixer_result=""


if [[ "$1" == "mute" ]]; then
    next_amixer_result=$(amixer set Master toggle)
elif [[ "$1" == "down" ]]; then
    next_amixer_result=$(amixer set Master $STEP%- unmute)
elif [[ "$1" == "up" ]]; then
    next_amixer_result=$(amixer set Master $STEP%+ unmute)
fi

vol=$(echo "$next_amixer_result" | grep -Po "[0-9]+(?=%)" | tail -1)
state=$(echo "$next_amixer_result" | grep -o "off" | head -n 1)

if [[ "$state" == *"off"* ]]; then
    level="Mute"
    vol="0"
else
    level="$vol%"
fi

if [[ "$prev_vol" -ne "$vol" || ("$prev_state" == *"off"* && "$state" != *"off"* ) ]]; then
    pacat --file-format=wav ~/.config/sway/sounds/volume.wav &
fi

~/.config/sway/actions/notify-progress "Volume $level" "$vol"
