#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

STEP=${2:-3}

prev_vol=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
prev_off=$(amixer get Master | grep -o "off" | head -n 1)

if [[ "$1" == "mute" || "$prev_off" == *"off"* ]]; then
    echo `amixer set Master toggle` > /dev/null
fi

if [[ "$1" == "down" ]]; then
    echo `amixer set Master $STEP%-` > /dev/null
elif [[ "$1" == "up" ]]; then
    echo `amixer set Master $STEP%+` > /dev/null
fi

vol=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
off=$(amixer get Master | grep -o "off" | head -n 1)

if [[ "$1" == "mute" && "$off" == *"off"* ]]; then
    level="Mute"
    vol="0"
else
    scaled=$(echo "scale=2; $vol / 100.0" | bc)
    level="$vol%"
fi

~/.config/sway/actions/notify-progress "Volume $level" "$vol"

if [[ "$prev_vol" -ne "$vol" || ("$prev_off" == *"off"* && "$off" != *"off"* ) ]]; then
    pacat --file-format=wav ~/.config/sway/sounds/volume.wav &
fi
