#!/usr/bin/env bash

set -e

function section {
  echo
  echo
  echo
  echo "########################################"
  echo "$1"
  echo "########################################"
  echo
}

function ask {
  printf "%s: " "$2"
  read $1
}

function askyesno {
  AFFIRMATIVE=${3:-yes}
  NEGATIVE=${4:-no}
  while [ "${!1}" != "$AFFIRMATIVE" ] && [ "${!1}" != "$NEGATIVE" ]; do
    ask $1 "$2 ($AFFIRMATIVE/$NEGATIVE)"
  done
}


# NOTE(JL): Assumes Laptop, Lenovo X1 Carbon 8th Gen
section "INSTALLING PACKAGES"
pacman -S \
  git \
  sudo \
  vim \
  networkmanager \
  nm-connection-editor \
  gnome-keyring \
  sof-firmware \
  tlp \
  tlp-rdw \
  acpi_call \
  lm_sensors \
  thermald \
  powertop \
  ;
  # acpi_call \ # not needed once natacpi's discharge/recalibrate are merged
  #             # see https://linrunner.de/tlp/faq/battery.html
  # sof-firmware \ # is this needed?
  #                # see https://bbs.archlinux.org/viewtopic.php?id=257975

echo "Installing yay"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay


# https://wiki.archlinux.org/index.php/Installation_guide#Initramfs
# https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Configuring_mkinitcpio
section "ADDING ENCRYPT TO MKINITCPIO"
sed -i '/^HOOKS=/s/.*/HOOKS=(base udev autodetect keyboard keymap modconf block encrypt filesystems resume fsck)/' /etc/mkinitcpio.conf
mkinitcpio -p linux


# https://wiki.archlinux.org/index.php/Installation_guide#Time_zone
# https://wiki.archlinux.org/index.php/System_time#Time_standard
section "SETTING TIME"
# NOTE(JL): I don't think timedatectl runs in the right context during chroot
timedatectl set-timezone America/Los_Angeles
timedatectl set-local-rtc false
timedatectl set-ntp true
ln -f -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
hwclock --systohc --utc
systemctl enable systemd-timesyncd.service


# https://wiki.archlinux.org/index.php/Installation_guide#Localization
section "SETTING LOCALE"
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
export LANG=en_US.UTF-8
# https://wiki.archlinux.org/index.php/Linux_console/Keyboard_configuration#Creating_a_custom_keymap
mkdir -p /usr/local/share/kbd/keymaps
echo "keycode 58 = Escape" > /usr/local/share/kbd/keymaps/personal.map
echo "KEYMAP=/usr/local/share/kbd/keymaps/personal.map" > /etc/vconsole.conf


# https://wiki.archlinux.org/index.php/Installation_guide#Network_configuration
section "SETTING NETWORK"
ask HOSTNAME "Hostname"
echo "$HOSTNAME" > /etc/hostname
cat >> /etc/hosts <<EOL
127.0.0.1 localhost
::1       localhost
127.0.0.1 ${HOSTNAME}.localdomain ${HOSTNAME}
EOL
systemctl enable NetworkManager.service
cp /etc/iptables/simple_firewall.rules /etc/iptables/iptables.rules
systemctl enable iptables.service


section "SETTING USER"
# https://wiki.archlinux.org/index.php/Installation_guide#Root_password
echo "Setting root password"
passwd
# https://wiki.archlinux.org/index.php/Users_and_groups#Example_adding_a_user
echo "Creating regular user account"
ask USERNAME "Username"
# https://wiki.archlinux.org/index.php/Users_and_groups#User_groups
# docker group?
# sys group? (printers)
useradd -m -g users -G wheel,storage,power,sys,audio,video,input "$USERNAME"
passwd "$USERNAME"
mkdir /home/"$USERNAME"/Desktop
mkdir /home/"$USERNAME"/Documents
mkdir /home/"$USERNAME"/Downloads
mkdir /home/"$USERNAME"/Music
mkdir /home/"$USERNAME"/Pictures
mkdir /home/"$USERNAME"/Videos
echo "Adding wheel group to sudoers"
sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
cat >> /etc/sudoers <<EOL
Defaults timestamp_timeout=15
Defaults passprompt="[sudo] password for %u: "
Defaults lecture=never
EOL


section "SETTING PERFORMANCE/MAINTENANCE"
# https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM
systemctl enable fstrim.timer
# https://wiki.archlinux.org/index.php/TLP#Installation
systemctl enable tlp.service
systemctl enable NetworkManager-dispatcher.service # For tlp-rdw
systemctl mask systemd-rfkill.service
systemctl mask systemd-rfkill.socket
systemctl enable thermald.service
# https://wiki.archlinux.org/index.php/Fan_speed_control#ThinkPad_laptops
yay -S thinkfan
modprobe thinkpad_acpi
echo "options thinkpad_acpi fan_control=1" > /etc/modprobe.d/thinkfan.conf
cat > /etc/thinkfan.conf <<EOL
sensors:
  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [1,2,3,4,5]
fans:
  - tpacpi: /proc/acpi/ibm/fan
levels:
  - [0, 0, 50]
  - ["level auto", 45, 75]
  - ["level disengaged", 70, 255]
EOL
systemctl enable thinkfan


# section "SETTING CONFIG"
echo "Cloning dotfiles into /home/$USERNAME/.config"
git clone https://github.com/jiexi/....git /home/"$USERNAME"/.config


# TODO(JL): Consider https://wiki.archlinux.org/index.php/Laptop
# Lenovo audio and mic mute LED
