#!/usr/bin/env bash

set -e

function section {
  echo
  echo
  echo
  echo "########################################"
  echo "$1"
  echo "########################################"
  echo
}


function ask {
  printf "%s: " "$2"
  read $1
}

section "INSTALLING PACKAGES NEEDED AFTER REBOOT"
ask WIFI "Install wifi-menu? (yes/no)"
[ "$WIFI" == "yes" ] && pacman -S dialog wpa_supplicant
pacman -S \
  dhcpcd \
  netctl \
  sudo \
  vi \
  ;

section "ADDING ENCRYPT TO MKINITCPIO"
# https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Configuring_mkinitcpio
# TODO(JL): Make this with insert automated
echo "Manual step"
echo "Vim will be opened on /etc/mkinitcpio.conf"
echo "Ensure `keyboard`, `keymap`, and `encrypt` exist in HOOKS()"
ask TMP "Press any key to continue"
vim /etc/mkinitcpio.conf
mkinitcpio -p linux

section "SETTING LOCALE"
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
export LANG=en_US.UTF-8
ln -f -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
ask HOSTNAME "Hostname"
echo "$HOSTNAME" > /etc/hostname

# TODO(JL): Add /etc/hosts?

section "SETTING ROOT PASSWORD"
passwd

section "CREATING MAIN USER"
ask USERNAME "Username"
useradd -m -g users -G wheel "$USERNAME"
passwd "$USERNAME"

section "SETTING UP SIMPLE FIREWALL"
cp /etc/iptables/simple_firewall.rules /etc/iptables/iptables.rules
systemctl enable iptables.service
